const CONFIG = {
    GAME: {
        CELL_SIZE: 30,
        FPS: 60,
        INVINCIBLE_DURATION: 3000,
        RESPAWN_COUNTDOWN: 10,
        FOOD_SCORE: 10,
        DEFAULT_BGM_VOLUME: 50,
        DEFAULT_SFX_VOLUME: 100,
    },
    LEVELS: {
        1: {
            name: '初級',
            subtitle: 'のんびり散歩',
            gridCols: 20,
            gridRows: 12,
            speed: 220,
            foodLifetime: Infinity,
            maxFood: 1,
            hasObstacles: false,
            obstacles: [],
            hasMovingBarriers: false,
            hasAI: false,
            winScore: 200,
        },
        2: {
            name: '中級',
            subtitle: '障害物回避',
            gridCols: 20,
            gridRows: 12,
            speed: 180,
            foodLifetime: 10000,
            maxFood: 2,
            hasObstacles: true,
            obstacles: [
                {x: 5, y: 3}, {x: 5, y: 4}, {x: 5, y: 5},
                {x: 14, y: 6}, {x: 14, y: 7}, {x: 14, y: 8},
                {x: 9, y: 2}, {x: 10, y: 2},
                {x: 9, y: 9}, {x: 10, y: 9},
            ],
            hasMovingBarriers: true,
            barrierInterval: 15000,
            barrierLifetime: 12000,
            barrierWarning: 3000,
            hasAI: false,
            winScore: 500,
        },
        3: {
            name: '高級',
            subtitle: '終極挑戦',
            gridCols: 25,
            gridRows: 15,
            speed: 145,
            foodLifetime: 8000,
            maxFood: 3,
            hasObstacles: true,
            obstacles: [
                {x: 6, y: 4}, {x: 6, y: 5}, {x: 6, y: 6}, {x: 6, y: 7},
                {x: 18, y: 4}, {x: 18, y: 5}, {x: 18, y: 6}, {x: 18, y: 7},
                {x: 12, y: 3}, {x: 12, y: 4},
                {x: 12, y: 10}, {x: 12, y: 11},
            ],
            hasMovingBarriers: true,
            barrierInterval: 10000,
            barrierLifetime: 10000,
            barrierWarning: 3000,
            hasAI: true,
            aiSpeed: 180,
            aiInitLength: 3,
            aiMaxLength: 15,
            winScore: 1000,
        },
    },
    COLORS: {
        BG: '#0a0a1a',
        GRID_LINE: '#151530',
        SNAKE_HEAD: '#00d4ff',
        SNAKE_BODY: '#7b2ff7',
        FOOD: '#ff2d78',
        FOOD_GLOW: '#ff2d78',
        OBSTACLE: '#ff4444',
        OBSTACLE_WARNING: '#ff8800',
        BARRIER: '#ff6600',
        BARRIER_WARNING: '#ffaa00',
        AI_HEAD: '#ff0066',
        AI_BODY: '#cc0055',
        AI_EYE: '#ff0000',
        INVINCIBLE: '#00ffcc',
        TEXT_PRIMARY: '#ffffff',
        TEXT_SECONDARY: '#8888aa',
        NEON_BLUE: '#00d4ff',
        NEON_PURPLE: '#7b2ff7',
        NEON_PINK: '#ff2d78',
    },
    SKINS: {
        presets: [
            {id: 'neon', name: 'ネオン', head: '#00d4ff', body: '#7b2ff7'},
            {id: 'fire', name: 'ファイア', head: '#ff4400', body: '#ff8800'},
            {id: 'forest', name: 'フォレスト', head: '#00ff66', body: '#008844'},
            {id: 'gold', name: 'ゴールド', head: '#ffdd00', body: '#ff8800'},
            {id: 'phantom', name: 'ファントム', head: '#cc00ff', body: '#6600cc'},
        ],
        custom: [
            {id: 1, color: '#ff0000', name: '赤'},
            {id: 2, color: '#ff6600', name: '橙'},
            {id: 3, color: '#ffcc00', name: '黄'},
            {id: 4, color: '#00ff00', name: '緑'},
            {id: 5, color: '#00ffff', name: '青'},
            {id: 6, color: '#0066ff', name: '藍'},
            {id: 7, color: '#9900ff', name: '紫'},
            {id: 8, color: '#ff00ff', name: '品紅'},
            {id: 9, color: '#ff0088', name: '桃'},
            {id: 10, color: '#ffffff', name: '白'},
            {id: 11, color: '#888888', name: '灰'},
            {id: 12, color: '#000000', name: '黒'},
        ],
    },
    STORAGE_KEY: 'neonSnakeDojo_v2',
    JP: {
        TITLE: 'ネオンヘビ',
        SUBTITLE: '霓虹蛇道',
        START: 'スタート',
        LEVEL_SELECT: 'レベル選択',
        SKIN: 'スキン',
        SETTINGS: '設定',
        HOME: 'ホーム',
        PAUSE: '一時停止',
        RESUME: '再開',
        QUIT: '終了',
        GAME_OVER: 'ゲームオーバー',
        VICTORY: 'クリア！',
        SCORE: 'スコア',
        BEST: '最高',
        REVIVE: '復活する',
        NEXT_LEVEL: '次へ',
        WATCH_AD: '広告を見て復活',
        SOUND_ON: '🔊',
        SOUND_OFF: '🔇',
        HEAD: '頭',
        BODY: '体',
        OPACITY: '透明度',
        BGM: 'BGM',
        SFX: '効果音',
        RESET: 'リセット',
        CONFIRM: '確定',
        CANCEL: 'キャンセル',
        DRAG_HINT: 'ドラッグして適用',
        INVINCIBLE: '無敵',
        LV: 'LV',
    },
};

window.CONFIG = CONFIG;
